using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Models.ApplicationUser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Interfaces.ApplicationUser
{
    [ControllerOfEntity(Constants.EntityNames.ApplicationUser)]
    public partial interface IApplicationUserController
    {
    }
}
