// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedSystem.DataAccess.Models
{
    public partial class ApplicationUserOrder
    {
        [Key]
        public long ApplicationuserOrderId { get; set; }
        public long ApplicationUserId { get; set; }
        [Column(TypeName = "money")]
        public decimal OrderTotal { get; set; }
        public DateTimeOffset OrderDate { get; set; }

        [ForeignKey("ApplicationUserId")]
        [InverseProperty("ApplicationUserOrder")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}