// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedSystem.DataAccess.Models
{
    [Index("ApplicationUserOrderId", "ProductId", Name = "UI_ApplicationUserOrderDetail_Product", IsUnique = true)]
    public partial class ApplicationUserOrderDetail
    {
        [Key]
        public long ApplicationUserOrderDetailId { get; set; }
        public long ApplicationUserOrderId { get; set; }
        public long ProductId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        public decimal LineTotal { get; set; }

        [ForeignKey("ApplicationUserOrderId")]
        [InverseProperty("ApplicationUserOrderDetail")]
        public virtual ApplicationUserOrder ApplicationUserOrder { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("ApplicationUserOrderDetail")]
        public virtual Product Product { get; set; }
    }
}