// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AutoGeneratedSystem.DataAccess.Models
{
    [Index("Name", Name = "UI_Product_Name", IsUnique = true)]
    public partial class Product
    {
        public Product()
        {
            ApplicationUserOrderDetail = new HashSet<ApplicationUserOrderDetail>();
        }

        [Key]
        public long ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string ImageUrl { get; set; }
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }

        [InverseProperty("Product")]
        public virtual ICollection<ApplicationUserOrderDetail> ApplicationUserOrderDetail { get; set; }
    }
}