namespace AutoGeneratedSystem.Common
{
    public static class Constants
    {
        public static class EntityNames
        {
            public const string ApplicationUser = nameof(ApplicationUser);
        }
    }
}