namespace AutoGeneratedSystem.Common
{
    public static class Constants
    {
        public static class PageRoutes
        {
            public static class ApplicationUserOrderRoutes
            {
                public const string Create = "/ApplicationUserOrder/Create";
                public const string List = "/ApplicationUserOrder/List";
            }
            public static class ProductRoutes
            {
                public const string Create = "/Product/Create";
                public const string List = "/Product/List";
            }
            public static class ApplicationUserApplicationRoleRoutes
            {
                public const string Create = "/ApplicationUserApplicationRole/Create";
                public const string List = "/ApplicationUserApplicationRole/List";
            }
            public static class StoreRoutes
            {
                public const string Create = "/Store/Create";
                public const string List = "/Store/List";
            }
            public static class CompanyRoutes
            {
                public const string Create = "/Company/Create";
                public const string List = "/Company/List";
            }
            public static class ApplicationRoleRoutes
            {
                public const string Create = "/ApplicationRole/Create";
                public const string List = "/ApplicationRole/List";
            }
            public static class ApplicationUserRoutes
            {
                public const string Create = "/ApplicationUser/Create";
                public const string List = "/ApplicationUser/List";
            }
        }
        public static class EntityNames
        {
            public const string ApplicationUser = nameof(ApplicationUser);
            public const string ApplicationRole = nameof(ApplicationRole);
            public const string Store = nameof(Store);
            public const string Company = nameof(Company);
            public const string ApplicationUserApplicationRole = nameof(ApplicationUserApplicationRole);
            public const string Product = nameof(Product);
            public const string ApplicationUserOrder = nameof(ApplicationUserOrder);
        }
    }
}