using AutoGeneratedSystem.ClientServices;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.AutomatedTests.ClientServices
{
    [TestClass]
    public class ApplicationUserClientServiceTests: TestsBase
    {
        [TestMethod]
        public async Task GetAllApplicationUserAsync()
        {
            ApplicationUserClientService applicationUserClientService = base.CreateApplicationUserClientService();
            var result = await applicationUserClientService.GetAllApplicationUserAsync();
            Assert.IsNotNull(result);
        }
    }
}
