using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;

namespace AutoGeneratedSystem.ClientServices
{
    [ClientServiceOfEntity(entityName:Constants.EntityNames.ApplicationUserOrderDetail,
        primaryKeyType:typeof(long))]
    public partial class ApplicationUserOrderDetailClientService
    {
    }
}
