using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.ClientServices
{
    [ClientServiceOfEntity(Constants.EntityNames.ApplicationUser)]
    public partial class ApplicationUserClientService
    {
    }
}
