using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Common;

namespace AutoGeneratedSystem.ClientServices
{
    [ClientServiceOfEntity(entityName:Constants.EntityNames.ApplicationUserOrder,
        primaryKeyType:typeof(long))]
    public partial class ApplicationUserOrderClientService
    {
    }
}
