using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.ApplicationUserApplicationRole
{
    public class ApplicationUserApplicationRoleModel
    {
        public long ApplicationUserApplicationRoleId { get; set; }
        public long ApplicationUserId { get; set; }
        public short ApplicationRoleId { get; set; }
    }
}
