using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Common;

namespace AutoGeneratedSystem.Models.ApplicationUserApplicationRole
{
    public class CreateApplicationUserApplicationRoleModel
    {
        [Required]
        [JunctionTable(nameof(Constants.EntityNames.ApplicationUser))]
        public long? ApplicationUserId { get; set; }
        [Required]
        [JunctionTable(nameof(Constants.EntityNames.ApplicationRole))]
        public short? ApplicationRoleId { get; set; }
    }
}
