using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Common;

namespace AutoGeneratedSystem.Models.ApplicationUserApplicationRole
{
    public class CreateApplicationUserApplicationRoleModel
    {
        [Required]
        [JunctionTable(nameof(Constants.EntityNames.ApplicationUser),
            nameof(Models.ApplicationUser.ApplicationUserModel.Name),
            nameof(Models.ApplicationUser.ApplicationUserModel.ApplicationUserId))]
        public long? ApplicationUserId { get; set; }
        [Required]
        [JunctionTable(nameof(Constants.EntityNames.ApplicationRole),
            nameof(Models.ApplicationRole.ApplicationRoleModel.RoleName),
            nameof(Models.ApplicationRole.ApplicationRoleModel.ApplicationRoleId))]
        public short? ApplicationRoleId { get; set; }
    }
}
