using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedSystem.Models.ApplicationUserOrderDetail
{
    public class ApplicationUserOrderDetailModel
    {
        [Required]
        public long? ApplicationUserOrderDetailId { get; set; }
        [Required]
        public long? ApplicationUserOrderId { get; set; }
        [Required]
        public long? ProductId { get; set; }
        [Required]
        public int? Quantity { get; set; }
        [Required]
        public decimal? LineTotal { get; set; }
    }
}
