using AutoGeneratedSystem.DataAccess.Models;
using AutoGeneratedSystem.Models.ApplicationUser;
using AutoMapper;

namespace AutoGeneratedSystem.Server.AutoMapperProfiles
{
    public class GlobalProfile: Profile
    {
        public GlobalProfile()
        {
            CreateMap<CreateApplicationUserModel, ApplicationUser>();

            CreateMap<ApplicationUserModel, ApplicationUser>();
            CreateMap<ApplicationUser, ApplicationUserModel>();
        }
    }
}
