using AutoGeneratedSystem.DataAccess.Data;
using AutoGeneratedSystem.Server;
using AutoGeneratedSystem.Services;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
var services = builder.Services;
Startup.ConfigureServices(services, builder.Configuration);

var app = builder.Build();
Startup.ConfigureApp(app);

app.Run();

public partial class Program { }