using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Common;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(entityName:Constants.EntityNames.ApplicationUserOrder,
        primaryKeyType:typeof(long))]
    public partial class ApplicationUserOrderService
    {
    }
}
