using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(entityName:Constants.EntityNames.ApplicationRole, primaryKeyType: typeof(short))]
    public partial class ApplicationRoleService
    {
    }
}
