using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.DataAccess.Models;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(entityName:Constants.EntityNames.ApplicationUser, 
        primaryKeyType: typeof(long))]
    public partial class ApplicationUserService
    {
    }
}