using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(Constants.EntityNames.ApplicationUser)]
    public class ApplicationUserService
    {

    }
}