using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(Constants.EntityNames.ApplicationUser, createFile:true)]
    public partial class ApplicationUserService
    {

    }
}