using System.Threading.Tasks;
using AutoGeneratedSystem.DataAccess.Data;
using AutoGeneratedSystem.DataAccess.Models;
using System.Linq;
namespace AutoGeneratedSystem.Services
{
public partial class ApplicationUserService
{
private readonly AutogeneratedsystemDatabaseContext _autogeneratedsystemDatabaseContext;
public ApplicationUserService(AutogeneratedsystemDatabaseContext autogeneratedsystemDatabaseContext)
{
_autogeneratedsystemDatabaseContext = autogeneratedsystemDatabaseContext;
}
public async Task<ApplicationUser> CreateApplicationUserAsync(ApplicationUser entity, CancellationToken cancellationToken)
{
await _autogeneratedsystemDatabaseContext.ApplicationUser.AddAsync(entity,cancellationToken);
await _autogeneratedsystemDatabaseContext.SaveChangesAsync(cancellationToken);
return entity;
}
public IQueryable<ApplicationUser> GetAllApplicationUser(CancellationToken cancellationToken)
{
return _autogeneratedsystemDatabaseContext.ApplicationUser;
}
}
}
