using System.Threading.Tasks;
using AutoGeneratedSystem.DataAccess.Data;
using AutoGeneratedSystem.DataAccess.Models;
using System.Linq;
namespace AutoGeneratedSystem.Services
{
public partial class ApplicationRoleService
{
private readonly AutogeneratedsystemDatabaseContext _autogeneratedsystemDatabaseContext;
public ApplicationRoleService(AutogeneratedsystemDatabaseContext autogeneratedsystemDatabaseContext)
{
_autogeneratedsystemDatabaseContext = autogeneratedsystemDatabaseContext;
}
public async Task<ApplicationRole> CreateApplicationRoleAsync(ApplicationRole entity, CancellationToken cancellationToken)
{
await _autogeneratedsystemDatabaseContext.ApplicationRole.AddAsync(entity,cancellationToken);
await _autogeneratedsystemDatabaseContext.SaveChangesAsync(cancellationToken);
return entity;
}
public IQueryable<ApplicationRole> GetAllApplicationRole(CancellationToken cancellationToken)
{
return _autogeneratedsystemDatabaseContext.ApplicationRole;
}
}
}
