using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(Common.Constants.EntityNames.Company)]
    public partial class CompanyService
    {
    }
}

