using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity(entityName: Common.Constants.EntityNames.Company, 
        primaryKeyType:typeof(long))]
    public partial class CompanyService
    {
    }
}

