using System.Threading.Tasks;
using AutoGeneratedSystem.DataAccess.Data;
using AutoGeneratedSystem.DataAccess.Models;
using System.Linq;
namespace AutoGeneratedSystem.Services
{
public partial class CompanyService
{
private readonly AutogeneratedsystemDatabaseContext _autogeneratedsystemDatabaseContext;
public CompanyService(AutogeneratedsystemDatabaseContext autogeneratedsystemDatabaseContext)
{
_autogeneratedsystemDatabaseContext = autogeneratedsystemDatabaseContext;
}
public async Task<Company> CreateCompanyAsync(Company entity, CancellationToken cancellationToken)
{
await _autogeneratedsystemDatabaseContext.Company.AddAsync(entity,cancellationToken);
await _autogeneratedsystemDatabaseContext.SaveChangesAsync(cancellationToken);
return entity;
}
public IQueryable<Company> GetAllCompany(CancellationToken cancellationToken)
{
return _autogeneratedsystemDatabaseContext.Company;
}
}
}
