using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Services
{
    [ServiceOfEntity( entityName: Constants.EntityNames.Store, 
        primaryKeyType:typeof(long))]
    public partial class StoreService
    {
    }
}
