using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoGeneratedSystem.Common.CustomAttributes;

namespace AutoGeneratedSystem.Models.Store
{
    public class CreateStoreModel
    {
        [Required]
        [StringLength(50)]
        public string? Name { get; set; }
        [Required]
        [Url]
        [ImageUrl]
        [StringLength(250)]
        public string? ImageUrl { get; set; }
    }
}
