using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.Store
{
    public class DeleteStoreModel
    {
        public long StoreId { get; set; }
    }
}
