using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using Microsoft.AspNetCore.Mvc;

namespace AutoGeneratedSystem.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [ControllerOfEntity(Constants.EntityNames.ApplicationUser)]
    public partial class ApplicationUserController : ControllerBase, IApplicationUserController
    {
    }
}
