using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;

namespace AutoGeneratedSystem.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [ControllerOfEntity(entityName: Constants.EntityNames.ApplicationUserOrderDetail,
        primaryKeyType: typeof(long))]
    public partial class ApplicationUserOrderDetailController : ControllerBase
    {
    }
}
