using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.DataAccess.Models;
using AutoGeneratedSystem.Models.ApplicationUser;
using AutoGeneratedSystem.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AutoGeneratedSystem.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [ControllerOfEntity(Constants.EntityNames.ApplicationUser, typeof(long))]
    public partial class ApplicationUserController : ControllerBase
    {
        //[HttpGet("[action]")]
        //public async Task<ApplicationUserModel> GetApplicationUserById([FromQuery]long primarykeyValue, [FromServices] ApplicationUserService ApplicationUserService, [FromServices] IMapper mapper, CancellationToken cancellationToken)
        //{
        //    var entity = await ApplicationUserService.GetApplicationUserByIdAsync(primarykeyValue, cancellationToken);
        //    var result = mapper.Map<ApplicationUser, ApplicationUserModel>(entity);
        //    return result;
        //}
    }
}
