using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Common.CustomAttributes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AutoGeneratedSystem.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [ControllerOfEntity(Constants.EntityNames.Store, typeof(long))]
    public partial class StoreController : ControllerBase
    {
    }
}
