using System;
using System.Collections.Generic;
using System.Text;

namespace AutoGeneratedSystem.Client.Generators
{
    public class AutoGeneratedPages
    {
        public bool Create { get; set; }
        public bool List { get; set; }
    }

}
