using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;

namespace AutoGeneratedSystem.Client.Generators
{
    public class RazorPageAdditionalText : AdditionalText
    {
        private readonly string _text;

        public override string Path { get; }

        public RazorPageAdditionalText(string path)
        {
            Path = path;
            _text = File.ReadAllText(path);
        }

        public override SourceText GetText(CancellationToken cancellationToken = new CancellationToken())
        {
            return SourceText.From(_text);
        }
    }
}
