using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.MauiBlazor.Components
{
    public class DynamicMenuModel
    {
        public string Title { get; set; }
        public string CssClass { get; set; }
    }
}
