using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.ApplicationRole
{
    public class ApplicationRoleModel
    {
        public short ApplicationRoleId { get; set; }
        [Required]
        [StringLength(50)]
        public string? RoleName { get; set; }
        [Required]
        [StringLength(50)]
        public string? RoleDescription { get; set; }
    }
}
