using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.ApplicationRole
{
    public class DeleteApplicationRoleModel
    {
        public short ApplicationRoleId { get; set; }
    }
}
