using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.ApplicationUser
{
    public class DeleteApplicationUserModel
    {
        public long ApplicationUserId { get; set; }
    }
}
