using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Common.CustomAttributes
{
    [AttributeUsage(AttributeTargets.Interface | AttributeTargets.Class)]
    public class ControllerOfEntityAttribute : Attribute
    {
        public string EntityName { get; private set; }
        public ControllerOfEntityAttribute(string entityName)
        {
            this.EntityName = entityName;
        }
    }
}
