using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Common.CustomAttributes
{
    [AttributeUsage(AttributeTargets.Property)]
    public class ImageUrlAttribute: Attribute
    {
    }
}
