using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Common.CustomAttributes
{
    [AttributeUsage(AttributeTargets.Property)]
    public class JunctionTableAttribute: Attribute
    {
        public string EntityName { get; }
        public JunctionTableAttribute(string entityName)
        {
            this.EntityName = entityName;
        }
    }
}
