using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Common.CustomAttributes
{
    [AttributeUsage(AttributeTargets.Interface | AttributeTargets.Class)]
    public class ServiceOfEntityAttribute : Attribute
    {
        public string EntityName { get; private set; }
        public bool CreateFile { get; private set; }
        public ServiceOfEntityAttribute(string entityName, bool createFile)
        {
            this.EntityName = entityName;
            this.CreateFile = createFile;
        }
    }
}
