using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AutoGeneratedSystem.Models.ApplicationUserOrder
{
    public class ApplicationUserOrderModel
    {
        [Required]
        public long? ApplicationUserOrderId { get; set; }
        [Required]
        public long? ApplicationUserId { get; set; }
        [Required]
        public decimal? OrderTotal { get; set; }
        [Required]
        public DateTimeOffset? OrderDate { get; set; }
    }
}
