using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AutoGeneratedSystem.Common.CustomAttributes;
using AutoGeneratedSystem.Common;

namespace AutoGeneratedSystem.Models.ApplicationUserOrder
{
    public class CreateApplicationUserOrderModel
    {
        [Required]
        [JunctionTable(entityName:Constants.EntityNames.ApplicationUser,
            displayTextFieldName:nameof(ApplicationUser.ApplicationUserModel.Name),
            valueFieldName:nameof(ApplicationUser.ApplicationUserModel.ApplicationUserId))]
        public long? ApplicationUserId { get; set; }
        [Required]
        public decimal? OrderTotal { get; set; }
        [Required]
        public DateTimeOffset? OrderDate { get; set; }

    }
}
