using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedSystem.Models.Company
{
    public class DeleteCompanyModel
    {
        public long CompanyId { get; set; }
    }
}
