using AutoGeneratedSystem.Client;
using AutoGeneratedSystem.ClientServices;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Blazored.Toast;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddHttpClient($"AutoGeneratedSystem.ServerAPI.Anonymous", client =>
                client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));

builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>()
                .CreateClient($"AutoGeneratedSystem.ServerAPI.Anonymous"));
builder.Services.AddBlazoredToast();
builder.Services.AddTransient<HttpClientService>();
builder.Services.AddTransient<ApplicationUserClientService>();
builder.Services.AddTransient<ApplicationRoleClientService>();
builder.Services.AddTransient<CompanyClientService>();
builder.Services.AddTransient<ApplicationUserApplicationRoleClientService>();
builder.Services.AddTransient<StoreClientService>();

await builder.Build().RunAsync();
