using AutoGeneratedSystem.Models.ApplicationRole;
using Microsoft.AspNetCore.Components;
using AutoGeneratedSystem.ClientServices;
namespace AutoGeneratedSystem.Client.Pages.ApplicationRole
{
public partial class Create
{
[Inject]
ApplicationRoleClientService ApplicationRoleClientService { get; set; }
private CreateApplicationRoleModel Model {get;set;} = new();
private async Task OnValidSubmitAsync()
{
var result = await this.ApplicationRoleClientService.CreateApplicationRoleAsync(this.Model);
}
}
}
