using AutoGeneratedSystem.ClientServices;
using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Models.ApplicationRole;
using Microsoft.AspNetCore.Components;
using Blazored.Toast.Services;
namespace AutoGeneratedSystem.Client.Pages.ApplicationRole
{
[Route(Constants.PageRoutes.ApplicationRoleRoutes.List)]
public partial class List
{
[Inject]
ApplicationRoleClientService ApplicationRoleClientService { get; set; }
[Inject]
private IToastService ToastService { get;set; }
[Inject] private NavigationManager NavigationManager { get; set; }
private ApplicationRoleModel[] AllApplicationRole { get; set; }
private bool IsLoading {get; set;}
protected override async Task OnInitializedAsync()
{
try
{
this.IsLoading = true;
this.AllApplicationRole = await ApplicationRoleClientService.GetAllApplicationRoleAsync();
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading=false;
}
}
private async Task DeleteApplicationRoleAsync(ApplicationRoleModel model)
{
try
{
this.IsLoading = true;
await this.ApplicationRoleClientService.DeleteApplicationRoleAsync(model);
this.AllApplicationRole = await ApplicationRoleClientService.GetAllApplicationRoleAsync();
ToastService.ShowSuccess($"ApplicationRole with id {model.ApplicationRoleId} has been deleted");
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading = false;
}
}
}
}
