using AutoGeneratedSystem.ClientServices;
using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Models.ApplicationUserOrder;
using Microsoft.AspNetCore.Components;
using Blazored.Toast.Services;
namespace AutoGeneratedSystem.Client.Pages.ApplicationUserOrder
{
[Route(Constants.PageRoutes.ApplicationUserOrderRoutes.List)]
public partial class List
{
[Inject]
ApplicationUserOrderClientService ApplicationUserOrderClientService { get; set; }
[Inject]
private IToastService ToastService { get;set; }
[Inject] private NavigationManager NavigationManager { get; set; }
private ApplicationUserOrderModel[] AllApplicationUserOrder { get; set; }
private bool IsLoading {get; set;}
protected override async Task OnInitializedAsync()
{
try
{
this.IsLoading = true;
this.AllApplicationUserOrder = await ApplicationUserOrderClientService.GetAllApplicationUserOrderAsync();
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading=false;
}
}
private async Task DeleteApplicationUserOrderAsync(ApplicationUserOrderModel model)
{
try
{
this.IsLoading = true;
await this.ApplicationUserOrderClientService.DeleteApplicationUserOrderAsync(model);
this.AllApplicationUserOrder = await ApplicationUserOrderClientService.GetAllApplicationUserOrderAsync();
ToastService.ShowSuccess($"ApplicationUserOrder with id {model.ApplicationUserOrderId} has been deleted");
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading = false;
}
}
}
}
