using AutoGeneratedSystem.ClientServices;
using AutoGeneratedSystem.Common;
using AutoGeneratedSystem.Models.Product;
using Microsoft.AspNetCore.Components;
using Blazored.Toast.Services;
namespace AutoGeneratedSystem.Client.Pages.Product
{
[Route(Constants.PageRoutes.ProductRoutes.List)]
public partial class List
{
[Inject]
ProductClientService ProductClientService { get; set; }
[Inject]
private IToastService ToastService { get;set; }
[Inject] private NavigationManager NavigationManager { get; set; }
private ProductModel[] AllProduct { get; set; }
private bool IsLoading {get; set;}
protected override async Task OnInitializedAsync()
{
try
{
this.IsLoading = true;
this.AllProduct = await ProductClientService.GetAllProductAsync();
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading=false;
}
}
private async Task DeleteProductAsync(ProductModel model)
{
try
{
this.IsLoading = true;
await this.ProductClientService.DeleteProductAsync(model);
this.AllProduct = await ProductClientService.GetAllProductAsync();
ToastService.ShowSuccess($"Product with id {model.ProductId} has been deleted");
}
catch (Exception ex)
{
ToastService.ShowError(ex.Message);
}
finally
{
this.IsLoading = false;
}
}
}
}
